const words = [
    'arse',
    'arsehead',
    'arsehole',
    'ass',
    'asshole',
    'bastard',
    'bitch',
    'bloody',
    'bollocks',
    'brotherfucker',
    'bugger',
    'bullshit',
    'childfucker',
    'Christ on a bike',
    'Christ on a cracker',
    'cock',
    'cocksucker',
    'crap',
    'cunt',
    'damn it',
    'dick',
    'dick-head',
    'dickhead',
    'dumb ass',
    'dyke',
    'faggot',
    'fatherfucker',
    'fuck',
    'fucker',
    'fucking',
    'god dammit',
    'hell',
    'holy shit',
    'horseshit',
    'in shit',
    'jackarse',
    'jackass',
    'kike',
    'motherfucker',
    'nigga',
    'nigger',
    'pigfucker',
    'piss',
    'prick',
    'pussy',
    'shit',
    'shit ass',
    'shite',
    'sibling fucker',
    'sisterfuck',
    'sisterfucker',
    'slut',
    'son of a bitch',
    'son of a whore',
    'spastic',
    'sweet Jesus',
    'twat',
    'wanker',
            ];
    const words2 = [
                'arse',
                'arsehead',
                'arsehole',
                'ass',
                'asshole',
                'bastard',
                'bitch',
                'bloody',
                'bollocks',
                'brotherfucker',
                'bugger',
                'bullshit',
                'childfucker',
                'Christ on a bike',
                'Christ on a cracker',
                'cock',
                'cocksucker',
                'crap',
                'cunt',
                'damn it',
                'dick',
                'dick-head',
                'dickhead',
                'dumb ass',
                'dyke',
                'faggot',
                'fatherfucker',
                'fuck',
                'fucker',
                'fucking',
                'god dammit',
                'hell',
                'holy shit',
                'horseshit',
                'in shit',
                'jackarse',
                'jackass',
                'kike',
                'motherfucker',
                'nigga',
                'nigger',
                'pigfucker',
                'piss',
                'prick',
                'pussy',
                'shit',
                'shit ass',
                'shite',
                'sibling fucker',
                'sisterfuck',
                'sisterfucker',
                'slut',
                'son of a bitch',
                'son of a whore',
                'spastic',
                'sweet Jesus',
                'twat',
                'wanker',
                        ];